services:
  - type: web
    name: reactfood-backend
    rootDir: backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
